# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      token:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Введите INVEST_TOKEN:'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      account_id:
        description: 'Введите ACCOUNT_ID:'
        default: ''
        required: true
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Display Python version
      run: python3 -c "import sys; print(sys.version)"
    - name: install dependencies
      run: python3 -m pip install -r requirements.txt
    - name: run bot
      run: python3 src/run_trader.py ema -c config/ema_trader_moex.yaml
      env:
        INVEST_TOKEN: ${{ inputs.token }}
        ACCOUNT_ID: ${{ inputs.account_id }}
        SANDBOX_TOKEN: ${{ inputs.token }}
        PYTHONUNBUFFERED: "1"